# Generated by Django 3.0.3 on 2020-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AddField(
            model_name='blog',
            name='tagline',
            field=models.TextField(default='none'),
        ),
    ]
